baseURL = 'https://pious.men/'
languageCode = 'en-us'
title = 'Pious Men'
theme = 'hugo-theme-stack'


[params]

    favicon = "chain.webp"
    mainSections = ["posts"]

    [params.footer]
        since = 2025
        customText = "Stay in the Way!"

    [params.sidebar]
        compact = true
        subtitle = "Stay in the Way!"
        
    [params.sidebar.avatar]
        enabled = true
        local = true
        src = "chain.webp"

[[params.widgets.page]]
    type = "toc"
